import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from 'next/font/google'
import Sidebar from "./components/SideBar";

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // puedes ajustar los pesos que necesites
  variable: '--font-roboto',     // esto define una variable CSS opcional
})

export const metadata: Metadata = {
  title: "PandorAI Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="flex flex-col md:flex-row min-h-screen bg-gray-100 text-gray-900">
        <Sidebar />
        <main className=" p-2">
          {children}
        </main>
      </body>
    </html>
  );
}
