// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from 'next/font/google'
import BodyWrapper from "./components/BodyWrapper";

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "PandorAI Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      
        <BodyWrapper>{children}</BodyWrapper>

    </html>
  );
}
